### ISSUE TITLE
[Gazebo] laserscans drift away without movement

### ISSUE THREAD

**Issue by relffok** [relffok/mir_robot#1]
From time to time the laserscans drift towards the robot in a weird manner, even if robot is not moving.
only in gazebo!

more information following

**Comment by relffok** [comment]
this is caused by the robot tilting, inertia / weights / simulated properties must be checked

**Comment by mintar** [comment]
Wow, good find! I was also looking at the same issue right now.

For reference, here's a video of what's happening:

https://user-images.githubusercontent.com/320188/190986284-d7fb5dad-068e-4367-ac32-48ff3d0c5f42.mp4

**Comment by mintar** [comment]
I think this fixes it:

git cherry-pick 063d4e75d1414eb70c426b484967347e43faf54e

In noetic, the collision meshes for the wheels were replaced by cylinders. This solves lots of problems like this.

**Comment by relffok** [comment]
Nice, this helps indeed! Will pull this right away.
