### ISSUE TITLE
Rework collision meshes

### ISSUE THREAD

**Issue by relffok** [relffok/mir_robot#18]
* Missing collision mesh for [wheels](https://github.com/relffok/mir_robot/tree/galactic-devel/mir_description/meshes/visual) in [collision folder](https://github.com/relffok/mir_robot/tree/galactic-devel/mir_description/meshes/collision)
To speed up simulation, mesh needs to be scaled down and replaced in robot urdf [here](https://github.com/relffok/mir_robot/tree/galactic-devel/mir_description/meshes/collision) and [here](https://github.com/relffok/mir_robot/blob/29e1a473981e2a75be5bf6264ba851f4709b2f18/mir_description/urdf/include/mir_100_v1.urdf.xacro#L148)

* Check existing base mesh as well and improvement simulation when scaled down more

**Comment by OHeimann** [comment]
I'll try to look into it. Memo to myself!

**Comment by mintar** [comment]
This is no longer necessary. In noetic, the collision meshes for the wheels were replaced by cylinders:

git cherry-pick 063d4e75d1414eb70c426b484967347e43faf54e

**Comment by relffok** [comment]
done in: https://github.com/relffok/mir_robot/commit/39d13c9c48e0282fe732a15fb8d8cb49edc3ceca
